### ISSUE TITLE
[SYSTEM]: DND5e

### ISSUE THREAD

**Issue by Padhiver** [ZotyDev/objects-interactions-fx#32]
### Discord Username

Padhiver

### System

https://github.com/foundryvtt/dnd5e

### Notes on the Support

Hello !
I've been using your module since this morning, and it's really great! It's really simple.
I haven't encountered any stopping bugs, but I do get these two errors in the console every time I drag'n'drop an NPC from the sidebar to the canvas, and only NPCs.

I've tried this on a blank world and the same.

![image](https://github.com/ZotyDev/objects-interactions-fx/assets/80126915/23dcba22-180b-4b58-948d-21b31dacf05f)

Edit : The second error is certainly mine, it's the first to appear in a blank world.

**Comment by ZotyDev** [comment]
Hi! Thanks for reaching out and making a bug report! This is a error on the module, I will release a fix in some minutes. It is related to a obscure feature of OIF, the [Actor Invetor](https://modules.zoty.dev/oif/actorInventor.html) (note that I recommend everyone to not use it since its kinda buggy rn)
